### ISSUE TITLE
Simple Messenger.Get fails on macOS with System.Net.Sockets.SocketException: Protocol Option not supported

### ISSUE THREAD

**Issue by ChrisStaerkel** [lextm/sharpsnmplib#48]
Hello, 

when I try to run the following code 

`var result = Messenger.Get(VersionCode.V1, 
                           new IPEndPoint(IPAddress.Parse("192.168.1.2"), 161), 
                           new OctetString("public"),
                           new List<Variable>{new Variable(new ObjectIdentifier("1.3.6.1.2.1.1.1.0"))},
                           60000);`

from https://components.xamarin.com/gettingstarted/sharpsnmplib on my macOS setup, I get the following error: System.Net.Sockets.SocketOptionName 0x13 is not supported at IP level
Here is the Stacktrace:
`  at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, System.Int32 optionValue) [0x00029] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net.Sockets/Socket.cs:2447 \n  at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, System.Boolean optionValue) [0x00008] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net.Sockets/Socket.cs:2434 \n  at Lextm.SharpSnmpLib.Messaging.EndPointExtension.GetSocket (System.Net.EndPoint endpoint) [0x00024] in <1167d5085a7649e2940015ad221eb8f8>:0 \n  at Lextm.SharpSnmpLib.Messaging.SnmpMessageExtension.GetResponse (Lextm.SharpSnmpLib.Messaging.ISnmpMessage request, System.Int32 timeout, System.Net.IPEndPoint receiver) [0x00056] in <1167d5085a7649e2940015ad221eb8f8>:0 \n  at Lextm.SharpSnmpLib.Messaging.Messenger.Get (Lextm.SharpSnmpLib.VersionCode version, System.Net.IPEndPoint endpoint, Lextm.SharpSnmpLib.OctetString community, System.Collections.Generic.IList`1[T] variables, System.Int32 timeout) [0x00052] in <1167d5085a7649e2940015ad221eb8f8>:0 \n  at snmptest.MainClass.Main (System.String[] args) [0x0000c] in /Users/chris/Projects/snmptest/snmptest/Program.cs:16 "`

I am running mono 5.4.0.135 on macOS 10.13 Beta (17A306f)

I can provide a sample project if needed. Thanks!

**Comment by lextm** [comment]
There is significant difficult to debug the test cases on non-Windows platforms at this stage. So will defer investigation to a later time.

**Comment by lextm** [comment]
Fixed in master. Will be part of 10.0.0 release.

**Comment by ChrisStaerkel** [comment]
Thanks, I can confirm that it works on .NET Core without problems, however the issue remains in Mono (e.g. wehen I try to build a desktop application on the mac)

**Comment by lextm** [comment]
It is also an issue if you run it on Xamarin platforms.
